/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWatchlistRouteImport } from './routes/_app.watchlist'
import { Route as AppTransactionsRouteImport } from './routes/_app.transactions'
import { Route as AppRegistrarsRouteImport } from './routes/_app.registrars'
import { Route as AppRebalancingRouteImport } from './routes/_app.rebalancing'
import { Route as AppPriceHistoryRouteImport } from './routes/_app.price-history'
import { Route as AppNavHistoryRouteImport } from './routes/_app.nav-history'
import { Route as AppHoldingsRouteImport } from './routes/_app.holdings'
import { Route as AppDividendsRouteImport } from './routes/_app.dividends'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCompaniesRouteImport } from './routes/_app.companies'
import { Route as AppSettingsUsersRouteImport } from './routes/_app.settings.users'
import { Route as AppSettingsPriceEntryRouteImport } from './routes/_app.settings.price-entry'
import { Route as AppSettingsDeletedRecordsRouteImport } from './routes/_app.settings.deleted-records'
import { Route as AppSettingsDataUploadRouteImport } from './routes/_app.settings.data-upload'
import { Route as AppSettingsDataImportRouteImport } from './routes/_app.settings.data-import'
import { Route as AppSettingsCorporateActionsRouteImport } from './routes/_app.settings.corporate-actions'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistrarsRoute = AppRegistrarsRouteImport.update({
  id: '/registrars',
  path: '/registrars',
  getParentRoute: () => AppRoute,
} as any)
const AppRebalancingRoute = AppRebalancingRouteImport.update({
  id: '/rebalancing',
  path: '/rebalancing',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceHistoryRoute = AppPriceHistoryRouteImport.update({
  id: '/price-history',
  path: '/price-history',
  getParentRoute: () => AppRoute,
} as any)
const AppNavHistoryRoute = AppNavHistoryRouteImport.update({
  id: '/nav-history',
  path: '/nav-history',
  getParentRoute: () => AppRoute,
} as any)
const AppHoldingsRoute = AppHoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => AppRoute,
} as any)
const AppDividendsRoute = AppDividendsRouteImport.update({
  id: '/dividends',
  path: '/dividends',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPriceEntryRoute = AppSettingsPriceEntryRouteImport.update({
  id: '/settings/price-entry',
  path: '/settings/price-entry',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsDeletedRecordsRoute =
  AppSettingsDeletedRecordsRouteImport.update({
    id: '/settings/deleted-records',
    path: '/settings/deleted-records',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsDataUploadRoute = AppSettingsDataUploadRouteImport.update({
  id: '/settings/data-upload',
  path: '/settings/data-upload',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsDataImportRoute = AppSettingsDataImportRouteImport.update({
  id: '/settings/data-import',
  path: '/settings/data-import',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCorporateActionsRoute =
  AppSettingsCorporateActionsRouteImport.update({
    id: '/settings/corporate-actions',
    path: '/settings/corporate-actions',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/companies': typeof AppCompaniesRoute
  '/dashboard': typeof AppDashboardRoute
  '/dividends': typeof AppDividendsRoute
  '/holdings': typeof AppHoldingsRoute
  '/nav-history': typeof AppNavHistoryRoute
  '/price-history': typeof AppPriceHistoryRoute
  '/rebalancing': typeof AppRebalancingRoute
  '/registrars': typeof AppRegistrarsRoute
  '/transactions': typeof AppTransactionsRoute
  '/watchlist': typeof AppWatchlistRoute
  '/settings/corporate-actions': typeof AppSettingsCorporateActionsRoute
  '/settings/data-import': typeof AppSettingsDataImportRoute
  '/settings/data-upload': typeof AppSettingsDataUploadRoute
  '/settings/deleted-records': typeof AppSettingsDeletedRecordsRoute
  '/settings/price-entry': typeof AppSettingsPriceEntryRoute
  '/settings/users': typeof AppSettingsUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/companies': typeof AppCompaniesRoute
  '/dashboard': typeof AppDashboardRoute
  '/dividends': typeof AppDividendsRoute
  '/holdings': typeof AppHoldingsRoute
  '/nav-history': typeof AppNavHistoryRoute
  '/price-history': typeof AppPriceHistoryRoute
  '/rebalancing': typeof AppRebalancingRoute
  '/registrars': typeof AppRegistrarsRoute
  '/transactions': typeof AppTransactionsRoute
  '/watchlist': typeof AppWatchlistRoute
  '/': typeof AppIndexRoute
  '/settings/corporate-actions': typeof AppSettingsCorporateActionsRoute
  '/settings/data-import': typeof AppSettingsDataImportRoute
  '/settings/data-upload': typeof AppSettingsDataUploadRoute
  '/settings/deleted-records': typeof AppSettingsDeletedRecordsRoute
  '/settings/price-entry': typeof AppSettingsPriceEntryRoute
  '/settings/users': typeof AppSettingsUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/companies': typeof AppCompaniesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dividends': typeof AppDividendsRoute
  '/_app/holdings': typeof AppHoldingsRoute
  '/_app/nav-history': typeof AppNavHistoryRoute
  '/_app/price-history': typeof AppPriceHistoryRoute
  '/_app/rebalancing': typeof AppRebalancingRoute
  '/_app/registrars': typeof AppRegistrarsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/watchlist': typeof AppWatchlistRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/corporate-actions': typeof AppSettingsCorporateActionsRoute
  '/_app/settings/data-import': typeof AppSettingsDataImportRoute
  '/_app/settings/data-upload': typeof AppSettingsDataUploadRoute
  '/_app/settings/deleted-records': typeof AppSettingsDeletedRecordsRoute
  '/_app/settings/price-entry': typeof AppSettingsPriceEntryRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/companies'
    | '/dashboard'
    | '/dividends'
    | '/holdings'
    | '/nav-history'
    | '/price-history'
    | '/rebalancing'
    | '/registrars'
    | '/transactions'
    | '/watchlist'
    | '/settings/corporate-actions'
    | '/settings/data-import'
    | '/settings/data-upload'
    | '/settings/deleted-records'
    | '/settings/price-entry'
    | '/settings/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/companies'
    | '/dashboard'
    | '/dividends'
    | '/holdings'
    | '/nav-history'
    | '/price-history'
    | '/rebalancing'
    | '/registrars'
    | '/transactions'
    | '/watchlist'
    | '/'
    | '/settings/corporate-actions'
    | '/settings/data-import'
    | '/settings/data-upload'
    | '/settings/deleted-records'
    | '/settings/price-entry'
    | '/settings/users'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/companies'
    | '/_app/dashboard'
    | '/_app/dividends'
    | '/_app/holdings'
    | '/_app/nav-history'
    | '/_app/price-history'
    | '/_app/rebalancing'
    | '/_app/registrars'
    | '/_app/transactions'
    | '/_app/watchlist'
    | '/_app/'
    | '/_app/settings/corporate-actions'
    | '/_app/settings/data-import'
    | '/_app/settings/data-upload'
    | '/_app/settings/deleted-records'
    | '/_app/settings/price-entry'
    | '/_app/settings/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/watchlist': {
      id: '/_app/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/registrars': {
      id: '/_app/registrars'
      path: '/registrars'
      fullPath: '/registrars'
      preLoaderRoute: typeof AppRegistrarsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rebalancing': {
      id: '/_app/rebalancing'
      path: '/rebalancing'
      fullPath: '/rebalancing'
      preLoaderRoute: typeof AppRebalancingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/price-history': {
      id: '/_app/price-history'
      path: '/price-history'
      fullPath: '/price-history'
      preLoaderRoute: typeof AppPriceHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nav-history': {
      id: '/_app/nav-history'
      path: '/nav-history'
      fullPath: '/nav-history'
      preLoaderRoute: typeof AppNavHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/holdings': {
      id: '/_app/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof AppHoldingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dividends': {
      id: '/_app/dividends'
      path: '/dividends'
      fullPath: '/dividends'
      preLoaderRoute: typeof AppDividendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/price-entry': {
      id: '/_app/settings/price-entry'
      path: '/settings/price-entry'
      fullPath: '/settings/price-entry'
      preLoaderRoute: typeof AppSettingsPriceEntryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/deleted-records': {
      id: '/_app/settings/deleted-records'
      path: '/settings/deleted-records'
      fullPath: '/settings/deleted-records'
      preLoaderRoute: typeof AppSettingsDeletedRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/data-upload': {
      id: '/_app/settings/data-upload'
      path: '/settings/data-upload'
      fullPath: '/settings/data-upload'
      preLoaderRoute: typeof AppSettingsDataUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/data-import': {
      id: '/_app/settings/data-import'
      path: '/settings/data-import'
      fullPath: '/settings/data-import'
      preLoaderRoute: typeof AppSettingsDataImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/corporate-actions': {
      id: '/_app/settings/corporate-actions'
      path: '/settings/corporate-actions'
      fullPath: '/settings/corporate-actions'
      preLoaderRoute: typeof AppSettingsCorporateActionsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDividendsRoute: typeof AppDividendsRoute
  AppHoldingsRoute: typeof AppHoldingsRoute
  AppNavHistoryRoute: typeof AppNavHistoryRoute
  AppPriceHistoryRoute: typeof AppPriceHistoryRoute
  AppRebalancingRoute: typeof AppRebalancingRoute
  AppRegistrarsRoute: typeof AppRegistrarsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppWatchlistRoute: typeof AppWatchlistRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsCorporateActionsRoute: typeof AppSettingsCorporateActionsRoute
  AppSettingsDataImportRoute: typeof AppSettingsDataImportRoute
  AppSettingsDataUploadRoute: typeof AppSettingsDataUploadRoute
  AppSettingsDeletedRecordsRoute: typeof AppSettingsDeletedRecordsRoute
  AppSettingsPriceEntryRoute: typeof AppSettingsPriceEntryRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompaniesRoute: AppCompaniesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDividendsRoute: AppDividendsRoute,
  AppHoldingsRoute: AppHoldingsRoute,
  AppNavHistoryRoute: AppNavHistoryRoute,
  AppPriceHistoryRoute: AppPriceHistoryRoute,
  AppRebalancingRoute: AppRebalancingRoute,
  AppRegistrarsRoute: AppRegistrarsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppWatchlistRoute: AppWatchlistRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsCorporateActionsRoute: AppSettingsCorporateActionsRoute,
  AppSettingsDataImportRoute: AppSettingsDataImportRoute,
  AppSettingsDataUploadRoute: AppSettingsDataUploadRoute,
  AppSettingsDeletedRecordsRoute: AppSettingsDeletedRecordsRoute,
  AppSettingsPriceEntryRoute: AppSettingsPriceEntryRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
