DEFAULT_DOMAIN_CODES = [
    ("AUTH", "Authentication (login, logout, session, cookie)", "auth"),
    ("HOLD", "Holdings (CRUD, valuations, portfolios)", "holdings"),
    ("PRIC", "Prices (market price updates, CSV upload, quick entry)", "prices"),
    ("PRIH", "Price History (historical snapshots, charting data)", "price-history"),
    ("DASH", "Dashboard (overview, KPIs, charts)", "dashboard"),
    ("REGR", "Registrars (company registrars, contact, dividend mandates)", "registrars"),
    ("CLAM", "Claims (next rights issue, dividend claims)", "claims"),
    ("DIVD", "Dividends (declared, paid, reconciled)", "dividends"),
    ("TRAN", "Transactions (buy/sell, corp action bookings)", "transactions"),
    ("NAVH", "NAV History (fund NAV snapshots, performance)", "nav-history"),
    ("WTCH", "Watchlist (user watchlist, alerts)", "watchlist"),
    ("COMP", "Companies (company master, metadata, sector)", "companies"),
    ("ADMN", "Admin (user management, settings, audit log)", "admin"),
    ("USER", "Admin/Users (role management, invite flow)", "admin/users"),
    ("OBSD", "Obsidian Import (vault sync, markdown parsing)", "admin/obsidian"),
    ("CHAT", "Chat (AI ChatBot, intent router, response)", "chat"),
    ("SEC", "Security (authentication bypass, authorization, RBAC)", "../security"),
    ("INF", "Infrastructure (deploy pipeline, DB migration, Docker)", "../infrastructure"),
]
