DEFAULT_DOMAIN_CODES = [
    ("AUTH", "Authentication (login, logout, session, cookie)", "auth",
     '["LOGIN", "LOGOUT", "REFRESH", "CHANGE"]'),
    ("HOLD", "Holdings (CRUD, valuations, portfolios)", "holdings",
     '["CREATE", "UPDATE", "DELETE", "VIEW"]'),
    ("PRIC", "Prices (market price updates, CSV upload, quick entry)", "prices",
     '["UPDATE", "PARSE", "UPLOAD", "CSV", "QUICK", "REVERT"]'),
    ("PRIH", "Price History (historical snapshots, charting data)", "price-history",
     '["VIEW", "COMPARE", "EXPORT"]'),
    ("DASH", "Dashboard (overview, KPIs, charts)", "dashboard",
     '["VIEW", "FILTER", "EXPORT"]'),
    ("REGR", "Registrars (company registrars, contact, dividend mandates)", "registrars",
     '["CREATE", "UPDATE", "DELETE", "VIEW", "DOCUMENT"]'),
    ("CLAM", "Claims (next rights issue, dividend claims)", "claims",
     '["CREATE", "UPDATE", "VIEW", "SETTLE"]'),
    ("DIVD", "Dividends (declared, paid, reconciled)", "dividends",
     '["RECORD", "RECONCILE", "VIEW"]'),
    ("TRAN", "Transactions (buy/sell, corp action bookings)", "transactions",
     '["BUY", "SELL", "CORP", "VIEW"]'),
    ("NAVH", "NAV History (fund NAV snapshots, performance)", "nav-history",
     '["RECORD", "VIEW", "COMPARE"]'),
    ("WTCH", "Watchlist (user watchlist, alerts)", "watchlist",
     '["ADD", "REMOVE", "VIEW", "ALERT"]'),
    ("COMP", "Companies (company master, metadata, sector)", "companies",
     '["CREATE", "UPDATE", "VIEW", "MERGE"]'),
    ("ADMN", "Admin (user management, settings, audit log)", "admin",
     '["USER", "SETTINGS", "AUDIT"]'),
    ("USER", "Admin/Users (role management, invite flow)", "admin/users",
     '["CREATE", "INVITE", "ROLE", "VIEW"]'),
    ("OBSD", "Obsidian Import (vault sync, markdown parsing)", "admin/obsidian",
     '["SYNC", "PARSE", "IMPORT"]'),
    ("CHAT", "Chat (AI ChatBot, intent router, response)", "chat",
     '["SEND", "HISTORY", "ROUTE"]'),
    ("SEC", "Security (authentication bypass, authorization, RBAC)", "../security",
     '["AUTH", "RBAC", "PEN"]'),
    ("INF", "Infrastructure (deploy pipeline, DB migration, Docker)", "../infrastructure",
     '["DEPLOY", "MIGRATE", "DOCKER", "NETWORK"]'),
]