# BR-001 Gherkin Spec — UI Acceptance Tests (Dashboard, Holdings, Registrars)
# Generated by: Gherkin Spec Agent (Claude)
# Source: Draft test notes 2026-05-09 + BR-001-portfolio-tracking.md
# Covers: /dashboard | /holdings | /registrars
# Stack: FastAPI backend + Next.js frontend (pytest + httpx for API; Playwright for UI)
# Uncle Bob rule: Tests MUST fail before production code is written
#
# ═══════════════════════════════════════════════════════════════════════════════
# ARCHITECTURAL DECISIONS LOCKED
# ═══════════════════════════════════════════════════════════════════════════════
#
# Dashboard (/dashboard):
#   Read-only: page never enters edit mode — edit button must not render at all
#   Theme:     persisted via localStorage; survives hard refresh without flash
#   Notifications: overlay/popover pattern; each entry navigates to /settings/notifications
#   Action Items: four alert types —
#     1. Unclaimed dividends  (count + total naira amount)
#     2. Pending registrar document submissions (count)
#     3. Approved claims awaiting payout collection (company name)
#     4. Stale price warning (triggered when last update > 2 days ago)
#   Sector Allocation monthly delta: computed by diffing current NAV snapshot
#     against the snapshot taken on the first day of the current month.
#     Phase 2 dependency — deferred until NAV history is populated.
#   Top Holdings chart: bar chart, two toggle modes:
#     "By Value"  = ranked by current_price × num_shares (default)
#     "By Shares" = ranked by num_shares
#   Recent Transactions: five most recent records, ordered newest first.
#     Columns: date | ticker | type | shares | amount
#
# Holdings (/holdings):
#   Column phase map:
#     curr_value  → Phase 1 (price × shares; shows "—" when price is null)
#     cost_basis  → Phase 1 (stored on holding record)
#     return_%    → Phase 1 (simple return: (curr_value - cost_basis) / cost_basis)
#     div_yield   → Phase 2 (requires dividend records; shows "—" in Phase 1)
#     status      → Phase 1
#     actions     → Phase 1 (edit + delete)
#   Inline editing: clicking Edit on a row expands that row in place.
#     Only one row may be in edit mode at a time.
#     Clicking Edit on a second row exits the first without saving.
#     Cancel discards changes. Save sends PATCH /api/v1/holdings/{id}.
#   Delete: requires confirmation dialog before DELETE request is sent.
#   + Add Holding: Phase 1. Opens a modal — does NOT navigate to a new page.
#     Required fields: company (searchable select), shares,
#     avg purchase price, holding type, status.
#
# Registrars (/registrars):
#   Layout: left panel = registrar list; right panel = selected registrar detail.
#   Linked Companies card: "Link Company" reveals a company select dropdown.
#     Dropdown excludes companies already linked to this registrar.
#     Submit sends POST /api/v1/registrars/{id}/companies/{company_id}.
#   DEFECT (observed 2026-05-09): above POST returns HTTP 405.
#     Root cause: FastAPI router likely missing @router.post decorator or
#     route registered under wrong method. Must be fixed before SC-UI-041 passes.
#   Edit Registrar modal: pre-fills all current fields.
#     Dynamic key-value section: rows can be added ("Add field") and removed.
#     Each row: arbitrary string key + string value.
#     Use case: registrar has 4 phone numbers, 2 emails, custom reference codes.
#     Save sends PATCH /api/v1/registrars/{id} with all fields including dynamic ones.
#   Add Registrar modal: identical fields to Edit modal but empty on open.
#     Save sends POST /api/v1/registrars.
#   Delete Registrar: button sits alongside the Edit button (not in a menu).
#     Requires confirmation dialog. Dialog warns that linked company
#     associations will also be removed. Confirmed delete sends
#     DELETE /api/v1/registrars/{id}.
#
# Defect scenarios are marked [DEFECT] and are expected to FAIL
# until the underlying bug is resolved.
#
# Phase annotations:
#   Phase 1 = current sprint
#   Phase 2 = admin layer (dividends, registrar docs, claims)
#   Phase 4 = multi-portfolio (FR-12, deferred — no spec in this file)
#
# ═══════════════════════════════════════════════════════════════════════════════
# PAGE: /dashboard
# ═══════════════════════════════════════════════════════════════════════════════
#
# Dashboard is a read-only consolidation page.
# It never enters edit mode. It has no form submissions of its own.
# All data displayed is computed from other pages' records.
# ───────────────────────────────────────────────────────────────────────────────

Feature: Dashboard page — read-only consolidation view
  As a portfolio owner
  I want a single consolidated view of my portfolio state
  So that I can understand my net worth, pending actions, and performance at a glance

  Background:
    Given I am authenticated as an admin user
    And I am on the "/dashboard" page

  # ─── Edit button ──────────────────────────────────────────────────────────

  Scenario: SC-UI-001 Edit button does not appear on the dashboard
    When the page finishes loading
    Then no edit button is visible anywhere on the page
    And the page renders in read-only mode with no editable fields

  # ─── Theme toggle ─────────────────────────────────────────────────────────

  Scenario: SC-UI-002 Theme toggle switches from light mode to dark mode
    Given the current theme is "light"
    When I click the theme icon in the top navigation bar
    Then the page transitions to "dark" mode
    And the theme preference is persisted in localStorage as "dark"
    And refreshing the page preserves the "dark" theme without flash

  Scenario: SC-UI-003 Theme toggle switches from dark mode back to light mode
    Given the current theme is "dark"
    When I click the theme icon in the top navigation bar
    Then the page transitions to "light" mode
    And the theme preference is persisted in localStorage as "light"

  # ─── Notification icon ────────────────────────────────────────────────────

  Scenario: SC-UI-004 Clicking the notification icon opens a notification popover
    Given at least one notification exists in the system
    When I click the notification bell icon in the top navigation bar
    Then a notification popover appears
    And the popover lists the most recent notifications in reverse chronological order
    And each notification entry shows a short description and a relative timestamp

  Scenario: SC-UI-005 Clicking a notification entry navigates to /settings/notifications
    Given the notification popover is open
    When I click on any individual notification entry
    Then I am navigated to "/settings/notifications"
    And the popover closes

  Scenario: SC-UI-006 Notification popover closes when clicking outside it
    Given the notification popover is open
    When I click anywhere outside the popover
    Then the popover closes
    And I remain on "/dashboard"

  Scenario: SC-UI-007 Notification icon shows no popover when no notifications exist
    Given no notifications exist in the system
    When I click the notification bell icon
    Then a popover appears with an empty state message
    And no notification entries are listed

  # ─── Sector Allocation card ───────────────────────────────────────────────
  # Note: Monthly delta requires two NAV snapshots: one from the first day of
  # the current month and one from today. Phase 2 dependency.

  Scenario: SC-UI-008 Sector Allocation card displays current allocation percentages
    Given active holdings exist across at least two sectors
    When the page finishes loading
    Then the Sector Allocation card renders a donut or pie chart
    And each sector is labelled with its name and current percentage of total portfolio value

  Scenario: SC-UI-009 Sector Allocation card displays monthly change delta
    Given a NAV snapshot exists for the first day of the current month
    And a NAV snapshot exists for today with different sector weights
    When the page finishes loading
    Then each sector in the Sector Allocation card shows a monthly change value
    And the change is expressed as a positive or negative percentage point delta
    And sectors that grew show the delta in a success colour
    And sectors that shrank show the delta in a danger colour

  Scenario: SC-UI-010 Sector Allocation card shows empty state when no holdings exist
    Given no active holdings exist
    When the page finishes loading
    Then the Sector Allocation card shows an empty state message
    And no chart is rendered

  # ─── Top Holdings card ────────────────────────────────────────────────────

  Scenario: SC-UI-011 Top Holdings card renders a bar chart by value by default
    Given at least three active holdings exist with different current values
    When the page finishes loading
    Then the Top Holdings card displays a horizontal bar chart
    And holdings are ranked from highest to lowest current value
    And the "By Value" toggle button is active by default

  Scenario: SC-UI-012 Top Holdings card switches to ranking by number of shares
    Given the Top Holdings card is displaying "By Value"
    When I click the "By Shares" toggle button
    Then the bar chart re-renders with holdings ranked by number of shares held
    And the "By Shares" toggle button becomes active
    And the "By Value" toggle button becomes inactive

  Scenario: SC-UI-013 Top Holdings card switches back to ranking by value
    Given the Top Holdings card is displaying "By Shares"
    When I click the "By Value" toggle button
    Then the bar chart re-renders with holdings ranked by current portfolio value

  # ─── Recent Transactions card ─────────────────────────────────────────────

  Scenario: SC-UI-014 Recent Transactions card displays the five most recent transactions
    Given more than five transaction records exist
    When the page finishes loading
    Then the Recent Transactions card shows exactly five rows
    And each row displays: date, ticker, transaction type, number of shares, and transaction amount
    And rows are ordered with the most recent transaction first

  Scenario: SC-UI-015 Recent Transactions card shows empty state when no transactions exist
    Given no transaction records exist
    When the page finishes loading
    Then the Recent Transactions card shows an empty state message
    And no transaction rows are rendered

  Scenario: SC-UI-016 Recent Transactions date column shows current formatted date
    Given a transaction was created today
    When the page finishes loading
    Then the transaction row shows today's date in the date column
    And the date format is consistent across all rows

  # ─── Action Items card ────────────────────────────────────────────────────
  # Action Items surfaces four types of outstanding administrative tasks.
  # Each action type links to the relevant management page.

  Scenario: SC-UI-017 Action Items card displays unclaimed dividend alert with count
    Given one or more dividend records exist with status "unclaimed"
    When the page finishes loading
    Then the Action Items card shows an "Unclaimed dividends" entry
    And the entry includes a count of unclaimed dividend records
    And the entry includes the total unclaimed amount in naira

  Scenario: SC-UI-018 Action Items card displays pending registrar document alert
    Given one or more registrar document records exist with status "pending_submission"
    When the page finishes loading
    Then the Action Items card shows a "Registrar documents awaiting submission" entry
    And the entry includes a count of outstanding document submissions

  Scenario: SC-UI-019 Action Items card displays approved claim awaiting collection
    Given one or more claim records exist with status "approved"
    And those claims have not been marked as paid
    When the page finishes loading
    Then the Action Items card shows a "Claim approved — collect payout" entry
    And the entry includes the name of the company whose claim was approved

  Scenario: SC-UI-020 Action Items card displays stale price warning
    Given the most recent price update for any holding was more than two days ago
    When the page finishes loading
    Then the Action Items card shows a "Prices not updated" warning
    And the warning states the number of days since the last price update

  Scenario: SC-UI-021 Action Items card shows empty state when all actions are resolved
    Given no unclaimed dividends exist
    And no registrar documents are pending submission
    And no approved claims are awaiting collection
    And all holdings have been priced within the last two days
    When the page finishes loading
    Then the Action Items card shows an "All clear" or equivalent empty state message
    And no alert entries are rendered

  Scenario: SC-UI-022 Clicking an Action Items entry navigates to the relevant page
    Given the Action Items card shows an "Unclaimed dividends" entry
    When I click the "Unclaimed dividends" entry
    Then I am navigated to the dividends management page
    And the dividends list is filtered to show only unclaimed records


# ═══════════════════════════════════════════════════════════════════════════════
# PAGE: /holdings
# ═══════════════════════════════════════════════════════════════════════════════
#
# Holdings page shows two tables: Active Portfolio and Claims Portfolio.
# Phase annotations per column:
#   status        → Phase 1 (current)
#   actions       → Phase 1 (current)
#   curr_value    → Phase 1 (computed from price × shares — price may be null)
#   cost_basis    → Phase 1 (stored on holding record)
#   return_%      → Phase 1 (computed: (curr_value - cost_basis) / cost_basis)
#   div_yield     → Phase 2 (requires dividend records)
#
# Edit mode: inline row editing. The row expands in place.
# No separate edit page. Price corrections redirect to /settings/price-entry.
# + Add Holding: Phase 1, opens a modal (not a separate page).
# ───────────────────────────────────────────────────────────────────────────────

Feature: Holdings page — portfolio table and inline editing
  As a portfolio owner
  I want to view and manage all my holdings in one place
  So that I can keep my portfolio data accurate

  Background:
    Given I am authenticated as an admin user
    And I am on the "/holdings" page

  # ─── Column rendering by phase ────────────────────────────────────────────

  Scenario: SC-UI-023 Holdings table renders all Phase 1 columns for active holdings
    Given at least one active holding exists with a current price
    When the page finishes loading
    Then the Active Portfolio table is visible
    And each row displays: ticker, company name, shares, current value, cost basis, return %, status, and actions
    And the "div yield" column is either hidden or shows a Phase 2 placeholder

  Scenario: SC-UI-024 Current value column shows null indicator when no price exists
    Given an active holding exists with no current price on record
    When the page finishes loading
    Then the current value cell for that holding shows a dash or "—" indicator
    And the return % cell for that holding also shows "—"

  Scenario: SC-UI-025 Return % is computed as simple return from cost basis
    Given an active holding with current value "54000.00" and cost basis "40000.00"
    When the page finishes loading
    Then the return % cell for that holding shows "+35.00%"

  Scenario: SC-UI-026 Div yield column is not populated in Phase 1
    Given the application is running in Phase 1
    When the page finishes loading
    Then the div yield column shows "—" or a deferred indicator for every holding row
    And no dividend yield values are computed or displayed

  Scenario: SC-UI-027 Claims Portfolio table is displayed separately below Active Portfolio
    Given at least one claim holding exists
    When the page finishes loading
    Then a separate Claims Portfolio section is visible below the Active Portfolio table
    And claim holdings do not appear in the Active Portfolio table
    And claim holdings show "—" for current value, cost basis, and return %

  # ─── Inline row editing ───────────────────────────────────────────────────

  Scenario: SC-UI-028 Clicking the edit action link puts that row into inline edit mode
    Given at least one active holding exists
    When I click the "Edit" action link for a holding row
    Then that row expands into an inline edit form within the table
    And all other rows remain in read-only display mode
    And the edit form shows editable fields: ticker, company, shares, avg purchase price, status
    And a "Save" button and a "Cancel" button appear within the expanded row

  Scenario: SC-UI-029 Saving an inline edit update persists the changes
    Given a holding row is in inline edit mode
    And I change the number of shares to "150"
    When I click the "Save" button
    Then a PATCH request is sent to "/api/v1/holdings/{id}" with the updated shares
    And the row exits inline edit mode
    And the row now displays "150" in the shares column

  Scenario: SC-UI-030 Cancelling an inline edit discards changes and restores the row
    Given a holding row is in inline edit mode
    And I change the number of shares to "999"
    When I click the "Cancel" button
    Then the row exits inline edit mode
    And the original share count is restored in the display
    And no API request is sent

  Scenario: SC-UI-031 Only one row can be in edit mode at a time
    Given holding row A is in inline edit mode
    When I click the "Edit" action link for holding row B
    Then row A exits edit mode without saving
    And row B enters inline edit mode

  Scenario: SC-UI-032 Clicking the delete action link shows a confirmation prompt
    Given at least one active holding exists
    When I click the "Delete" action link for a holding row
    Then a confirmation dialog appears asking the user to confirm deletion
    And the dialog states which holding will be deleted by ticker and company name

  Scenario: SC-UI-033 Confirming delete removes the holding from the table
    Given a confirmation dialog is open for a holding
    When I click the "Confirm" button in the dialog
    Then a DELETE request is sent to "/api/v1/holdings/{id}"
    And the holding row disappears from the table
    And a success toast notification confirms the deletion

  Scenario: SC-UI-034 Cancelling the delete confirmation leaves the holding unchanged
    Given a confirmation dialog is open for a holding
    When I click the "Cancel" button in the dialog
    Then no DELETE request is sent
    And the holding row remains in the table

  # ─── + Add Holding button ─────────────────────────────────────────────────

  Scenario: SC-UI-035 Clicking + Add Holding opens an add holding modal
    When I click the "+ Add Holding" button
    Then a modal dialog opens titled "Add Holding" or equivalent
    And the modal contains fields for: company (searchable select), shares, average purchase price, holding type, and status
    And the modal does not navigate away from "/holdings"

  Scenario: SC-UI-036 Submitting the add holding modal with valid data creates a new holding
    Given the Add Holding modal is open
    And I select a company from the company search field
    And I enter "100" for number of shares
    And I enter "380.00" for average purchase price
    And I select "active" for holding type
    When I click the "Save" or "Add" button in the modal
    Then a POST request is sent to "/api/v1/holdings"
    And the modal closes
    And the new holding appears in the Active Portfolio table

  Scenario: SC-UI-037 Add Holding modal shows validation errors for missing required fields
    Given the Add Holding modal is open
    When I click the "Save" button without filling in any fields
    Then validation error messages appear beside each required field
    And no POST request is sent
    And the modal remains open

  Scenario: SC-UI-038 Closing the add holding modal without saving discards the form
    Given the Add Holding modal is open
    And I have partially filled in the form
    When I click the close button or press Escape
    Then the modal closes
    And no POST request is sent
    And no new holding appears in the table


# ═══════════════════════════════════════════════════════════════════════════════
# PAGE: /registrars
# ═══════════════════════════════════════════════════════════════════════════════
#
# Registrars page has two panels:
#   Left panel  — list of registrar names (tabs/list items, clickable)
#   Right panel — detail view for the selected registrar, including
#                 a "Linked Companies" card with the ability to link companies
#
# Defect found in testing:
#   POST /api/v1/registrars/{id}/companies/{company_id} returns HTTP 405
#   This is a routing bug — the endpoint exists but the method is not allowed.
#   Spec'd below as SC-UI-[DEFECT]-048.
# ───────────────────────────────────────────────────────────────────────────────

Feature: Registrars page — registrar management and company linking
  As a portfolio owner
  I want to manage registrar records and link them to my holdings companies
  So that I can track document requirements and contacts per registrar

  Background:
    Given I am authenticated as an admin user
    And I am on the "/registrars" page

  # ─── Registrar selection ─────────────────────────────────────────────────

  Scenario: SC-UI-039 Clicking a registrar in the left panel loads its detail view
    Given at least one registrar record exists
    When I click on a registrar name in the left panel
    Then the right panel updates to show that registrar's details
    And the selected registrar name is highlighted in the left panel
    And the right panel shows: registrar name, contact fields, and the Linked Companies card

  # ─── Link company to registrar ────────────────────────────────────────────

  Scenario: SC-UI-040 Clicking the Link button in Linked Companies reveals the company select field
    Given a registrar is selected and its detail view is displayed
    When I click the "Link Company" or "+" button in the Linked Companies card
    Then a company select dropdown appears
    And the dropdown lists companies not already linked to this registrar

  Scenario: SC-UI-041 [DEFECT] Linking a selected company to a registrar succeeds
    Given a registrar is selected
    And the company select dropdown is visible
    And I have selected a company from the dropdown
    When I click the "Link Company" submit button
    Then a POST request is sent to "/api/v1/registrars/{id}/companies/{company_id}"
    And the response status is 200 or 201
    And the linked company appears in the Linked Companies card
    And no HTTP 405 error is returned
    And the company select field is hidden after successful linking

  # This scenario documents the current defect observed during testing.
  # The test must FAIL until the routing bug is fixed on the backend.
  Scenario: SC-UI-042 [DEFECT] Linking a company does not return HTTP 405
    Given a registrar is selected
    And a company is selected from the dropdown
    When I click the "Link Company" submit button
    Then the response status is not 405
    And an error message is not displayed to the user

  Scenario: SC-UI-043 An already-linked company does not appear in the link dropdown
    Given a registrar has company "Dangote Cement" already linked
    When I click the "Link Company" button
    Then "Dangote Cement" does not appear in the company select dropdown

  # ─── Edit registrar modal ─────────────────────────────────────────────────

  Scenario: SC-UI-044 Clicking "Edit Registrar" opens the edit modal with current data pre-filled
    Given a registrar is selected with name "Coronation Registrars" and contact data
    When I click the "Edit Registrar" button
    Then an "Edit Registrar" modal opens
    And the registrar name field is pre-filled with "Coronation Registrars"
    And all existing contact fields are pre-filled with their current values
    And existing dynamic key-value fields are displayed with their current keys and values

  Scenario: SC-UI-045 Edit Registrar modal supports adding extra dynamic key-value contact fields
    Given the Edit Registrar modal is open
    When I click the "Add field" or "+" button within the contact fields section
    Then a new row appears with an empty key input and an empty value input
    And I can type a custom key such as "Phone 3" and a corresponding value
    And I can add multiple additional rows by clicking "Add field" again

  Scenario: SC-UI-046 Edit Registrar modal supports removing a dynamic key-value field
    Given the Edit Registrar modal is open
    And at least one dynamic key-value field row exists
    When I click the remove icon on a key-value field row
    Then that row is removed from the form
    And the remaining rows are unaffected

  Scenario: SC-UI-047 Saving the Edit Registrar modal persists all fields including dynamic ones
    Given the Edit Registrar modal is open with one dynamic field "Phone 3" = "0800-CORONATION"
    When I click the "Save" button
    Then a PATCH request is sent to "/api/v1/registrars/{id}"
    And the request body includes the dynamic field "Phone 3" with value "0800-CORONATION"
    And the modal closes
    And the right panel updates to display the new field

  Scenario: SC-UI-048 Cancelling the Edit Registrar modal discards changes
    Given the Edit Registrar modal is open
    And I have modified the registrar name
    When I click the "Cancel" button or press Escape
    Then the modal closes
    And no PATCH request is sent
    And the registrar name is unchanged in the right panel

  # ─── Add registrar ────────────────────────────────────────────────────────

  Scenario: SC-UI-049 Clicking Add Registrar opens an add modal with the same fields as Edit
    When I click the "Add Registrar" button
    Then an "Add Registrar" modal opens with an empty name field
    And the modal contains the same contact fields as the Edit Registrar modal
    And the modal includes the same "Add field" button for dynamic key-value rows
    And no fields are pre-filled

  Scenario: SC-UI-050 Add Registrar modal supports adding dynamic key-value contact fields
    Given the Add Registrar modal is open
    When I click the "Add field" button multiple times
    Then multiple empty key-value rows appear
    And each row is independently editable

  Scenario: SC-UI-051 Saving the Add Registrar modal with valid data creates a new registrar
    Given the Add Registrar modal is open
    And I enter "DataMax Registrars" in the name field
    And I add a dynamic field "Phone 1" = "01-234-5678"
    When I click the "Save" or "Add" button
    Then a POST request is sent to "/api/v1/registrars"
    And the request body includes name "DataMax Registrars" and the dynamic field
    And the modal closes
    And "DataMax Registrars" appears in the left panel registrar list

  Scenario: SC-UI-052 Add Registrar modal shows validation error when name is empty
    Given the Add Registrar modal is open
    When I click the "Save" button without entering a name
    Then a validation error appears on the name field
    And no POST request is sent
    And the modal remains open

  # ─── Delete registrar ─────────────────────────────────────────────────────

  Scenario: SC-UI-053 A delete button is visible alongside the Edit Registrar button
    Given a registrar is selected and its detail view is displayed
    When the page finishes loading
    Then a "Delete" or "Delete Registrar" button is visible next to the "Edit Registrar" button

  Scenario: SC-UI-054 Clicking Delete Registrar shows a confirmation dialog
    Given a registrar is selected
    When I click the "Delete Registrar" button
    Then a confirmation dialog appears
    And the dialog states which registrar will be deleted by name
    And the dialog warns that linked company associations will also be removed

  Scenario: SC-UI-055 Confirming deletion removes the registrar from the system
    Given the delete confirmation dialog is open for a registrar
    When I click the "Confirm" or "Delete" button in the dialog
    Then a DELETE request is sent to "/api/v1/registrars/{id}"
    And the registrar is removed from the left panel list
    And the right panel returns to an empty or default state
    And a success toast notification confirms the deletion

  Scenario: SC-UI-056 Cancelling deletion leaves the registrar unchanged
    Given the delete confirmation dialog is open for a registrar
    When I click the "Cancel" button in the dialog
    Then no DELETE request is sent
    And the registrar remains in the left panel list
    And the right panel still shows the registrar's details


# ═══════════════════════════════════════════════════════════════════════════════
# TRACEABILITY MATRIX — UI SCENARIOS
# ═══════════════════════════════════════════════════════════════════════════════
#
# PAGE: /dashboard
# SC-UI-001  Edit button not visible on dashboard                  → SC-UI-001
# SC-UI-002  Theme toggle light → dark, persists in localStorage   → SC-UI-002
# SC-UI-003  Theme toggle dark → light, persists in localStorage   → SC-UI-003
# SC-UI-004  Notification icon opens popover                       → SC-UI-004
# SC-UI-005  Clicking notification entry navigates to /settings    → SC-UI-005
# SC-UI-006  Popover closes on outside click                       → SC-UI-006
# SC-UI-007  Empty state when no notifications                     → SC-UI-007
# SC-UI-008  Sector Allocation renders chart with percentages      → SC-UI-008
# SC-UI-009  Sector Allocation shows monthly change delta          → SC-UI-009
# SC-UI-010  Sector Allocation empty state when no holdings        → SC-UI-010
# SC-UI-011  Top Holdings bar chart by value (default)             → SC-UI-011
# SC-UI-012  Top Holdings switches to by shares                    → SC-UI-012
# SC-UI-013  Top Holdings switches back to by value                → SC-UI-013
# SC-UI-014  Recent Transactions shows 5 most recent rows          → SC-UI-014
# SC-UI-015  Recent Transactions empty state                       → SC-UI-015
# SC-UI-016  Recent Transactions date column format                → SC-UI-016
# SC-UI-017  Action Items — unclaimed dividends alert              → SC-UI-017
# SC-UI-018  Action Items — pending registrar documents alert      → SC-UI-018
# SC-UI-019  Action Items — approved claim awaiting collection     → SC-UI-019
# SC-UI-020  Action Items — stale price warning (>2 days)          → SC-UI-020
# SC-UI-021  Action Items — all clear empty state                  → SC-UI-021
# SC-UI-022  Action Items entry navigates to relevant page         → SC-UI-022
#
# PAGE: /holdings
# SC-UI-023  Phase 1 columns rendered for active holdings          → SC-UI-023
# SC-UI-024  Current value shows dash when no price exists         → SC-UI-024
# SC-UI-025  Return % computed correctly from cost basis           → SC-UI-025
# SC-UI-026  Div yield deferred in Phase 1                         → SC-UI-026
# SC-UI-027  Claims Portfolio table rendered separately            → SC-UI-027
# SC-UI-028  Edit action puts row into inline edit mode            → SC-UI-028
# SC-UI-029  Saving inline edit persists changes via PATCH         → SC-UI-029
# SC-UI-030  Cancelling inline edit discards changes               → SC-UI-030
# SC-UI-031  Only one row in edit mode at a time                   → SC-UI-031
# SC-UI-032  Delete action shows confirmation prompt               → SC-UI-032
# SC-UI-033  Confirming delete removes holding via DELETE          → SC-UI-033
# SC-UI-034  Cancelling delete leaves holding unchanged            → SC-UI-034
# SC-UI-035  + Add Holding opens modal (not new page)              → SC-UI-035
# SC-UI-036  Add Holding modal creates holding via POST            → SC-UI-036
# SC-UI-037  Add Holding validation errors on empty submit         → SC-UI-037
# SC-UI-038  Closing add modal without saving discards form        → SC-UI-038
#
# PAGE: /registrars
# SC-UI-039  Clicking registrar in left panel loads detail view    → SC-UI-039
# SC-UI-040  Link button reveals company select field              → SC-UI-040
# SC-UI-041  [DEFECT] Linking company succeeds (HTTP 200/201)      → SC-UI-041
# SC-UI-042  [DEFECT] Linking company does not return HTTP 405     → SC-UI-042
# SC-UI-043  Already-linked company excluded from dropdown         → SC-UI-043
# SC-UI-044  Edit Registrar modal pre-fills current data           → SC-UI-044
# SC-UI-045  Edit modal supports adding dynamic key-value fields   → SC-UI-045
# SC-UI-046  Edit modal supports removing dynamic key-value fields → SC-UI-046
# SC-UI-047  Save persists dynamic fields via PATCH                → SC-UI-047
# SC-UI-048  Cancel edit discards changes                          → SC-UI-048
# SC-UI-049  Add Registrar modal has same fields as Edit modal     → SC-UI-049
# SC-UI-050  Add modal supports dynamic key-value rows             → SC-UI-050
# SC-UI-051  Save Add Registrar creates record via POST            → SC-UI-051
# SC-UI-052  Add Registrar validation error on empty name          → SC-UI-052
# SC-UI-053  Delete button visible alongside Edit button           → SC-UI-053
# SC-UI-054  Delete button shows confirmation dialog               → SC-UI-054
# SC-UI-055  Confirming delete removes registrar via DELETE        → SC-UI-055
# SC-UI-056  Cancelling delete leaves registrar unchanged          → SC-UI-056
#
# ───────────────────────────────────────────────────────────────────────────────
# CUMULATIVE UI SCENARIO COUNT: 56
# DEFECT SCENARIOS (must fail until bug fixed): SC-UI-041, SC-UI-042
# PHASE 2 DEFERRED SCENARIOS: SC-UI-009 (monthly delta), SC-UI-026 (div yield)
# ───────────────────────────────────────────────────────────────────────────────
#
# OPEN ITEM — Backend routing defect to fix before SC-UI-041 can pass:
#   Route:   POST /api/v1/registrars/{registrar_id}/companies/{company_id}
#   Symptom: HTTP 405 Method Not Allowed
#   Cause:   Route likely registered as GET or not registered at all
#   Fix:     Verify FastAPI router includes:
#            @router.post("/registrars/{registrar_id}/companies/{company_id}")
#            and that the router is included in the main app with the correct prefix
